### ISSUE TITLE
Hubspot to Bigquery in Meltano: Bug encountered while running tap-hubspot test

### ISSUE THREAD

**Issue by SwetaPrabh** [potloc/tap-hubspot#57]
Here are the steps to recreate it:

**_Prerequisite:_**
**1. hubspot private app access token with permission to access the following:**
content
automation
oauth
forms
crm.objects.contacts.read
crm.objects.marketing_events.read
crm.schemas.contacts.read
crm.objects.companies.read
crm.objects.deals.read
crm.schemas.companies.read
crm.schemas.deals.read
analytics.behavioral_events.send

**2. BigQuery credential key**

**3. BQ Project name, dataset name and location**

_**Steps in running the pipeline**_
**First Phase: Ran locally on Darwin admin-MacBook-Pro 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64** on May 10th

1. Installed Meltano locally
2. extractor tap-hubspot (potloc variant)
meltano add extractor tap-hubspot --variant potloc
3. meltano config tap-hubspot set --interactive
4. meltano config tap-hubspot test
Added the hubspot token and date
_1st bug encountered :_  https://meltano.slack.com/archives/C01TCRBBJD7/p1683752205053579
```
Plugin configuration is invalid
singer_sdk.exceptions.FatalAPIError: 403 Client Error: Forbidden for path: /analytics/v2/views
```
Workaround was adding  "!analytics_views_v2.*"

**Tested locally with jsonl target and the pipeline ran**

5. Tried adding Bigquery target 

_2nd bug encountered:_  https://meltano.slack.com/archives/C01TCRBBJD7/p1683925727611359
`ImportError: dlopen(/Users/swetaprabha/Desktop/Analytics/meltano/hubspot-bigquery-poc/.meltano/loaders/target-bigquery/venv/lib/python3.10/site-packages/orjson/orjson.cpython-310-darwin.so, 0x0002): tried: '/Users/swetaprabha/Desktop/Analytics/meltano/hubspot-bigquery-poc/.meltano/loaders/target-bigquery/venv/lib/python3.10/site-packages/orjson/orjson.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))`

Suggested solution: Changing machine environment

**Second Phase: Tested on Google VM (Linux <name of VM> 5.10.0-22-cloud-amd64 #1 SMP Debian 5.10.178-3 (2023-04-22) x86_64 GNU/Linux)** on May 16th

1. Installed Meltano on my Virtual Environment
2. extractor tap-hubspot (potloc variant)
meltano add extractor tap-hubspot --variant potloc
3. meltano config tap-hubspot set --interactive
Added the hubspot token and date
4. meltano config tap-hubspot test

_1st bug encountered:_ https://meltano.slack.com/archives/C01TCRBBJD7/p1684325606236709
`ModuleNotFoundError: No module named 'singer'`

Some fixes were done (reference on the slack thread)

_2nd bug encountered:_  https://meltano.slack.com/archives/C01TCRBBJD7/p1684337720708699?thread_ts=1684325606.236709&cid=C01TCRBBJD7
```
Cannot list the selected attributes: Catalog discovery failed: command ['/home/swetaprabha/meltano/hubspot-bigquery/.meltano/extractors/tap-hubspot/venv/bin/tap-hubspot', '--config', '/home/swetaprabha/meltano/hubspot-bigquery/.meltano/run/tap-hubspot/tap.5c5ac625-d4e6-419a-9378-6d39185dbb07.config.json', '--discover'] returned 1 with stderr:
 Traceback (most recent call last):
 File "/home/swetaprabha/meltano/hubspot-bigquery/.meltano/extractors/tap-hubspot/venv/lib/python3.9/site-packages/tap_hubspot/client.py", line 173, in get_properties
  return res["results"]
KeyError: 'results'
```
Some fixes were done (reference on slack thread)

_3rd bug encountered:_  https://meltano.slack.com/archives/C01TCRBBJD7/p1684866298749999?thread_ts=1684325606.236709&cid=C01TCRBBJD7
```
Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

Plugin configuration is invalid
singer_sdk.exceptions.FatalAPIError: 401 Client Error: Unauthorized for path: /crm/v3/objects/contacts
```

This is the most recent error and I would appreciate if someone can take a look and help me build an end-end pipeline for my use case

**USE-CASE:**

Data from hubspot is extracted using hubspot-tap in meltano and loaded into Bigquery using bigquery target

My meltano.yml file

```
version: 1
default_environment: dev
project_id: f4b73f3e-2a05-43c0-9b24-17fae8300576
environments:
- name: dev
- name: staging
- name: prod
plugins:
 extractors:
 - name: tap-hubspot
   variant: potloc
   pip_url: git+https://github.com/potloc/tap-hubspot.git
   config:
     start_date: '2023-05-01'
   select:
   - '!analytics_views_v2'
   - contacts.*
 loaders:
 - name: target-bigquery
   variant: z3z1ma
   pip_url: git+https://github.com/z3z1ma/target-bigquery.git
   config:
     credentials_path: /Users/admin/Desktop/meltano/hubspot-bigquery-poc/bq.json
     project: growth-team
     dataset: Retail
     location: us-west1
     batch_size: 500
```
