### ISSUE TITLE
Why are many streams hard set to full table replication?

### ISSUE THREAD

**Issue by srpwnd** [potloc/tap-hubspot#62]
Hello,

there are many streams that have hard-coded `replication_method = "FULL_TABLE"`

Specifically it is these streams:

- [AssociationsDealsToCompaniesStream](https://github.com/potloc/tap-hubspot/blob/main/tap_hubspot/streams.py#L197)
- [AssociationsDealsToContactsStream](https://github.com/potloc/tap-hubspot/blob/main/tap_hubspot/streams.py#L229)
- [AssociationsContactsToDealsStream](https://github.com/potloc/tap-hubspot/blob/main/tap_hubspot/streams.py#L261)
- [AssociationsContactsToCompaniesStream](https://github.com/potloc/tap-hubspot/blob/main/tap_hubspot/streams.py#L293)
- [AssociationsCompaniesToContactsStream](https://github.com/potloc/tap-hubspot/blob/main/tap_hubspot/streams.py#L325)
- [AssociationsCompaniesToDealsStream](https://github.com/potloc/tap-hubspot/blob/main/tap_hubspot/streams.py#L357)
- [MarketingCampaignIdsStream](https://github.com/potloc/tap-hubspot/blob/main/tap_hubspot/marketing_streams.py#L101)
- [MarketingCampaignsStream](https://github.com/potloc/tap-hubspot/blob/main/tap_hubspot/marketing_streams.py#L129)
- [MarketingListsStream](https://github.com/potloc/tap-hubspot/blob/main/tap_hubspot/marketing_streams.py#L180)
- [MarketingListContactsStream](https://github.com/potloc/tap-hubspot/blob/main/tap_hubspot/marketing_streams.py#L217)

I checked few of the API endpoints and it seems they do not have `updated_at` field but could there be any other way to make these streams incremental?

For example I noticed that the **MarketingCampaignIdsStream** uses `email/public/v1/campaigns/by-id` endpoint but it could also use `email/public/v1/campaigns` endpoint that provides campaigns with changes and timestamp of latest change. This could be consecutively fed to the child **MarketingCampaignsStream** to only load campaign details for campaigns with new changes.

I extract the data from HubSpot every day and my extract time is at 3 hours which I think is unreasonable for to the small amount of changes that actually happen each day.

I'm happy to help with some improvements and create PRs but I wanted to know if there are any specific reasons behind these decisions first.

**Comment by srpwnd** [comment]
Hi @SBurwash, thank you for the response!

I'm a little bit confused about offering associations directly in the streams (note my limited knowledge of how singer taps work). I went to check my **contacts** and **deals** tables synced to my storage and both of these only contain `id` and `updatedAt` fields.

Do I have to adjust some configuration? I couldn't find any settings related to this.

**Comment by SBurwash** [comment]
Hi @srpwnd, my pleasure! 

I'm assuming that you are using meltano to use the singer tap? 

Have you configurated the [select](https://docs.meltano.com/reference/command-line-interface#select) setting in your project configurations to get all the information the deals and contacts streams? It would look something like this:
https://github.com/potloc/tap-hubspot/blob/567712d59f56f3261a42b9be573d4f00c0a0d635/meltano.yml#L27

If so, what does the command `meltano select --list` return for you?

**Comment by srpwnd** [comment]
I've had the following config:
```yaml
  extractors:
    - name: tap-hubspot
      variant: potloc
      select:
        - "*"
        - "!analytics_views_v2"
        - "!campaign_ids_v1"
        - "!campaigns_v1"
        - "!web_analytics_contacts_v3"
        - "!web_analytics_deals_v3"
        - "!forms_v3"
        - "!marketing_emails_v1"
        - "!workflows_v3"
```

I assumed that would give me everything, but running the `meltano select --list` resulted in this:

```
Enabled patterns:
        *
        !analytics_views_v2
        !campaign_ids_v1
        !campaigns_v1
        !web_analytics_contacts_v3
        !web_analytics_deals_v3
        !forms_v3
        !marketing_emails_v1
        !workflows_v3

Selected attributes:
        [automatic] associations_companies_contacts.id
        [automatic] associations_companies_contacts.toObjectId
        [automatic] associations_companies_deals.id
        [automatic] associations_companies_deals.toObjectId
        [automatic] associations_contacts_companies.id
        [automatic] associations_contacts_companies.toObjectId
        [automatic] associations_contacts_deals.id
        [automatic] associations_contacts_deals.toObjectId
        [automatic] associations_deals_companies.id
        [automatic] associations_deals_companies.toObjectId
        [automatic] associations_deals_contacts.id
        [automatic] associations_deals_contacts.toObjectId
        [automatic] calls.id
        [automatic] calls.updatedAt
        [automatic] companies.id
        [automatic] companies.updatedAt
        [automatic] contacts.id
        [automatic] contacts.updatedAt
        [automatic] deals.id
        [automatic] deals.updatedAt
        [automatic] list_contacts_v1.canonical
        [automatic] list_contacts_v1.listId
        [automatic] lists_v1.listId
        [automatic] meetings.id
        [automatic] meetings.updatedAt
        [automatic] owners.id
        [automatic] owners.updatedAt
        [automatic] properties_companies.name
        [automatic] properties_companies.updatedAt
        [automatic] properties_contacts.name
        [automatic] properties_contacts.updatedAt
        [automatic] properties_deals.name
        [automatic] properties_deals.updatedAt
        [automatic] properties_meetings.name
        [automatic] properties_meetings.updatedAt
```

Turns out I have to do the following to get all the fields:

```yaml
  extractors:
    - name: tap-hubspot
      variant: potloc
      select:
        - "*.*"
        - "!analytics_views_v2"
        - "!campaign_ids_v1"
        - "!campaigns_v1"
        - "!web_analytics_contacts_v3"
        - "!web_analytics_deals_v3"
        - "!forms_v3"
        - "!marketing_emails_v1"
        - "!workflows_v3"
```

This feels a bit unintuitive to be honest. I would expect that by default everything is selected. I don't think I came across similar behavior with any other extractor/tap that I have used but maybe I am also missing something crucial that caused this on my part.

But anyway, thank you for guiding me through this. I will now optimize selects to get only the data I truly need and will see if I get around to playing with the marketing stream.

**Comment by SBurwash** [comment]
@srpwnd Perfect! I'm happy I could help. A personal opinion as advice - I prefer to select streams by "inclusion" rather than "exclusion", in order to avoid any issues regarding syncing a stream I don't want.

```
  extractors:
    - name: tap-hubspot
      variant: potloc
      select:
        - deals.*
        - contacts.*
        - companies.*
        - ...
```

I'll be closing the issue, but please let me know if I can help with anything else!
