### ISSUE TITLE
Incremental loading seems not to be working?

### ISSUE THREAD

**Issue by BernardWez** [potloc/tap-hubspot#78]
I've been working on getting this tap to work today with Meltano and cannot seem to figure out how the incremental loading works.

I'm trying to write it to a MSQL database using a `target-mssql`. The initial `meltano run tap-hubspot target-mssql` writes all records, even despite what the start_date is configured to. Not sure if the way I've specified the `start_date` as shown underneath is appropriate?

All subsequent runs also keep extracting and loading all records. Feel like I'm just missing something trivial as the in the git repository it explicitly mentions that the tap: "Incrementally pulls data based on the input state"

```
  - name: tap-hubspot
    variant: potloc
    pip_url: git+https://github.com/potloc/tap-hubspot.git
    config:
      access_token: ${HUBSPOT_TOKEN}
      start_date: "2023-08-20T00:00:00Z"
      flattening_enabled: true
      flattening_max_depth: 1
    select:
    - contacts.properties.*
    - "!contacts.associations.*"
    - "!contacts.associations"
```
